export enum TreeStatus {
  GROWING = 'GROWING',
  ALIVE = 'ALIVE',
  WITHERED = 'WITHERED',
}

export enum TreeType {
  OAK = 'Oak',
  PINE = 'Pine',
  WILLOW = 'Willow',
  BAMBOO = 'Bamboo',
  CACTUS = 'Cactus',
}

export interface Tag {
  id: string;
  name: string;
  color: string;
  dailyGoal: number; // Number of sessions per day
}

export interface Task {
  id: string;
  tagId: string;
  name: string;
  dailyGoal: number;
}

export interface Tree {
  id: string;
  createdAt: number; // Timestamp
  durationMinutes: number;
  tagId: string;
  taskId?: string; // Optional link to a specific task
  status: TreeStatus;
  type: TreeType;
  aiStory?: string; // Generated by Gemini
}

export type View = 'TIMER' | 'FOREST' | 'STATS';